site_dir: '../siv3d.new.github.io'

# Project information
site_name: Siv3D
site_url: https://siv3d.github.io/
site_author: Ryo Suzuki
site_description: "Siv3D: A C++ library for creative coding" 

# Copyright
copyright: Copyright (c) 2012 - 2022, Ryo Suzuki<br>Copyright (c) 2012 - 2022, OpenSiv3D Project

# Theme
theme:
  name: material
  language: en
  palette:
    scheme: siv3d
  logo: 'assets/images/code-white-48dp.svg'
  favicon: 'assets/images/favicon.ico'
  features:
  - navigation.instant
  - navigation.tabs
  - navigation.indexes
  - navigation.top
  - search.suggest
  - search.highlight
  - content.code.annotate
  plugins:
  - search:
      lang: 
        - en
        - ja
extra:
  alternate:
    - name: English
      link: 
      lang: en
    - name: 日本語
      link: /ja-jp/
      lang: ja
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Siv3D/OpenSiv3D
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/siv3d/shared_invite/enQtNjM4NzQ0MzEyMzUzLTEzNDBkNWVkMTY0OGU5OWQxOTk3NjczMjk0OGJhYzJjOThjZjQ1YmYzMWU2NzQ5NTQ4ODg3NzE2ZmE0NmVlMTM
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Reputeless
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Siv3D
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - English: 
    - Getting started with Siv3D: index.md
    - Features: features.md
    - Release Notes: releases.md
    - Download:
      - Windows: download/windows.md
      - macOS: download/macos.md
      - Ubuntu: download/ubuntu.md
      - Web (VS): download/web-vs.md
      - Web (VSCode): download/web-vscode.md
    - Tutorial:
      - Tutorial: tutorial/tutorial.md
    - Community:
      - Community: community/community.md
      - Lectures: community/study-meeting.md
      - Dev-day (Jissoukai): community/dev-day.md
    - Acknowledgments: acknowledgments.md
  - 日本語: 
    - Siv3D をはじめよう: ja-jp/index.md
    - Siv3D の機能: ja-jp/features.md
    - リリースノート: ja-jp/releases.md
    - ダウンロード:
      - Windows: ja-jp/download/windows.md
      - macOS: ja-jp/download/macos.md
      - Ubuntu: ja-jp/download/ubuntu.md
      - Web (VS): ja-jp/download/web-vs.md
      - Web (VSCode): ja-jp/download/web-vscode.md
    - チュートリアル:
      - チュートリアル: ja-jp/tutorial/tutorial.md
    - 開発に参加する:
      - 報告や提案: ja-jp/develop/report.md
      - 自前ビルドの手順: ja-jp/develop/build.md
      - GitHub でコミットする: ja-jp/develop/commit.md
    - コミュニティ:
      - コミュニティ: ja-jp/community/community.md
      - Siv3D 勉強会: ja-jp/community/study-meeting.md
      - OpenSiv3D 実装会: ja-jp/community/dev-day.md
    - 謝辞: ja-jp/acknowledgments.md

