site_dir: '../siv3d.github.io'

# Project information
site_name: Siv3D
site_url: https://siv3d.github.io/
site_author: Ryo Suzuki
site_description: "Siv3D: A C++ library for creative coding" 

# Copyright
copyright: Copyright (c) 2012 - 2022, Ryo Suzuki<br>Copyright (c) 2012 - 2022, OpenSiv3D Project

# Theme
theme:
  name: material
  language: en
  palette:
    scheme: siv3d
  logo: 'assets/images/code-white-48dp.svg'
  favicon: 'assets/images/favicon.ico'
  features:
  - navigation.instant
  - navigation.tabs
  - navigation.indexes
  - navigation.top
  - search.suggest
  - search.highlight
  - content.code.annotate
  plugins:
  - search:
      lang: 
        - en
        - ja
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Siv3D/OpenSiv3D
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/siv3d/shared_invite/enQtNjM4NzQ0MzEyMzUzLTEzNDBkNWVkMTY0OGU5OWQxOTk3NjczMjk0OGJhYzJjOThjZjQ1YmYzMWU2NzQ5NTQ4ODg3NzE2ZmE0NmVlMTM
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Reputeless
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Siv3D
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - English: 
    - Getting started with Siv3D: index.md
    - Features: features.md
    - Release Notes: releases.md
    - Download:
      - Windows: download/windows.md
      - macOS: download/macos.md
      - Ubuntu: download/ubuntu.md
      - Web (VS): download/web-vs.md
      - Web (VSCode): download/web-vscode.md
    - Tutorial:
      - Tutorial: tutorial/tutorial.md
    - API:
      - Classes: api/classes.md
    - Community:
      - Community: community/community.md
      - Lectures: community/study-meeting.md
      - Dev-day (Jissoukai): community/dev-day.md
    - Mascot:
      - Mascot: mascot/mascot.md
      - Gallery: mascot/gallery.md
    - Acknowledgments: acknowledgments.md
  - 日本語: 
    - Siv3D をはじめよう: ja-jp/index.md
    - Siv3D の機能: ja-jp/features.md
    - リリースノート: ja-jp/releases.md
    - ダウンロード:
      - Windows: ja-jp/download/windows.md
      - macOS: ja-jp/download/macos.md
      - Ubuntu: ja-jp/download/ubuntu.md
      - Web (VS): ja-jp/download/web-vs.md
      - Web (VSCode): ja-jp/download/web-vscode.md
    - チュートリアル:
      - チュートリアル: ja-jp/tutorial/tutorial.md
    - 勉強会コース:
      - 0. Siv3D 勉強会: ja-jp/learn/about.md
#      - 1. はじめての Siv3D: ja-jp/learn/hello-siv3d.md
#      - 2. Siv3D の基本: ja-jp/learn/basic.md
#      - 3. 図形を描く: ja-jp/learn/shape.md
#      - 4. 動きを作る: ja-jp/learn/animation.md
#      - 5. 画像を描く: ja-jp/learn/texture.md
#      - 6. テキストを描く: ja-jp/learn/font.md
#      - 7. データ構造: ja-jp/learn/data-structure.md
#      - 8. GUI: ja-jp/learn/gui.md
#      - 9. キーボード: ja-jp/learn/keyboard.md
#      - 10. マウス: ja-jp/learn/mouse.md
#      - 11. 当たり判定: ja-jp/learn/geometry.md
#      - 12. その他の機能: ja-jp/learn/misc.md
#      - 演習 A - アイテム集めゲーム : ja-jp/learn/make-1.md
#      - 演習 B - 深さ優先探索の可視化 : ja-jp/learn/make-2.md
#      - 演習 C - 楽譜記述言語自作 : ja-jp/learn/make-3.md
#      - 演習 D - 模写アプリ改造 : ja-jp/learn/make-4.md
#      - 演習 E - 音ゲー基礎 : ja-jp/learn/make-5.md
#      - 演習 F - 脱出ゲーム : ja-jp/learn/make-6.md
#      - 演習 G - ノードベースプログラミング言語自作 : ja-jp/learn/make-6.md
    - API:
      - クラス一覧: ja-jp/api/classes.md
    - コミュニティ:
      - コミュニティ: ja-jp/community/community.md
      - Siv3D 勉強会: ja-jp/community/study-meeting.md
      - OpenSiv3D 実装会: ja-jp/community/dev-day.md
    - 開発に参加する:
      - 報告や提案: ja-jp/develop/report.md
      - 自前ビルドの手順: ja-jp/develop/build.md
      - GitHub でコミットする: ja-jp/develop/commit.md
    - マスコット:
      - マスコット: ja-jp/mascot/mascot.md
      - ギャラリー: ja-jp/mascot/gallery.md
    - 謝辞: ja-jp/acknowledgments.md

