site_dir: '../siv3d.github.io'

# Project information
site_name: Siv3D
site_description: "Siv3D: An open source C++17 library for creative coding" 
site_author: Ryo Suzuki
site_url: https://siv3d.github.io/

# Copyright
copyright: Copyright (c) 2018 - present, Ryo Suzuki<br>Copyright (c) 2018 - present, OpenSiv3D Project

# Theme
theme:
  name: 'material'
  language: 'en'
  favicon: 'assets/images/favicon.ico'
  logo:
    icon: 'code'
  palette:
    primary: 'blue'
    accent: 'blue'
  feature:
    tabs: true
extra:
  search:
    language: 'en'
  social:
    - type: 'github'
      link: 'https://github.com/Siv3D/OpenSiv3D'
    - type: 'twitter'
      link: 'https://twitter.com/Siv3D'
markdown_extensions:
  - admonition
  - codehilite
  - fontawesome_markdown
  - footnotes
  - meta
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - toc:
      permalink: true
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - siv3d_styles.css

# Page tree
nav:
  - English: 
    - Getting started with Siv3D: index.md
    - Sample:
      - Game: sample/game.md
      - Application: sample/app.md
      - Visual effect: sample/visual.md
      - Geme template: sample/game-template.md
    - Tutorial:
      - 1. First steps: tutorial/basic.md
      - 2. Drawing shapes: tutorial/shape.md
      - 3. Animation: tutorial/animation.md
      - 4. 2D intersection: tutorial/2d-intersection.md
      - 5. Drawing images: tutorial/texture.md
      - 6. Data structures: tutorial/data-structures.md
      - 7. Formatting and parsing: tutorial/formatting.md
      - 8. Using fonts: tutorial/font.md
      - 9. GUI: tutorial/gui.md
      - 10. Scene and window: tutorial/window.md
      - 11. Keyboard: tutorial/keyboard.md
      - 12. Mouse: tutorial/mouse.md
      - 13. Audio: tutorial/audio.md
      - 14. Random: tutorial/random.md
      - 15. 2D render states: tutorial/2d-renderstates.md
      - 16. Effect: tutorial/effect.md
      - 17. Asset management: tutorial/asset.md
      - 18. Text file: tutorial/text-file.md
      - 19. Configuration file: tutorial/config-file.md
      - 20. Embedded resource: tutorial/resource.md
      - 21. Binary file: tutorial/binary-file.md
      - 22. Scene management: tutorial/scene-manager.md
      - 99. Releasing your application: tutorial/release.md
    - Reference:
      - Emoji list: reference/emojis.md
      - Fullscreen: reference/fullscreen.md
      - JSON file: reference/json.md
      - Text encoding conversion: reference/unicode.md
      - 2D shadow: reference/2d-shadow.md
      - 2D geometry: reference/2d-geometry.md
      - NavMesh: reference/navmesh.md
      - Natural language processing: reference/nlp.md
      - Math parser: reference/math-parser.md
      - kd-tree: reference/kd-tree.md
      - Object detection: reference/objdetection.md
      - Gamepad: reference/gamepad.md
      - Network: reference/network.md
      - Twitter: reference/twitter.md
      - 2D particle system: reference/2d-particle.md
      - 2D physics: reference/2d-physics.md
    - Training:
      - Circles: training/1-1.md
      - Tic-tac-toe: training/2-1.md
    - API Reference: api/api.md
    - News:
      - What's new in v0.4.1: news/v041.md
      - What's new in v0.4.2: news/v042.md
      - What's new in v0.4.3: news/v043.md
    - Articles:
      - Mistakes made by new users: articles/mistakes.md
      - Troubleshooting: articles/troubleshooting.md
      - How to build OpenSiv3D: articles/build.md
    - Siv3D Store: store/store.md
    - Community: 
      - Community: community/community.md
      - Study meeting: community/study-meeting.md
      - Dev Day: community/dev-day.md
    - Logo: logo/logo.md
    - Mascot: mascot/mascot.md
    - Support: support/support.md
    - External websites: external/external.md
    - ğŸ’—Sponsors: sponsors/sponsors.md
  - æ—¥æœ¬èª:
    - Siv3D ã‚’ã¯ã˜ã‚ã‚ˆã†: ja-jp/index.md
    - ã‚µãƒ³ãƒ—ãƒ«:
      - ã‚²ãƒ¼ãƒ : ja-jp/sample/game.md
      - ã‚¢ãƒ—ãƒª: ja-jp/sample/app.md
      - ãƒ“ã‚¸ãƒ¥ã‚¢ãƒ«è¡¨ç¾: ja-jp/sample/visual.md
      - ã‚²ãƒ¼ãƒ é–‹ç™ºã®ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆ: ja-jp/sample/game-template.md
      - ã‚²ãƒ¼ãƒ ãƒ©ãƒ³ãƒãƒ£ãƒ¼: ja-jp/sample/game-launcher.md
    - ãƒãƒ¥ãƒ¼ãƒˆãƒªã‚¢ãƒ«:
      - 1. Siv3D ã®åŸºæœ¬: ja-jp/tutorial/basic.md
      - 2. å›³å½¢ã‚’æã: ja-jp/tutorial/shape.md
      - 3. å‹•ãã‚’ä½œã‚‹: ja-jp/tutorial/animation.md
      - 4. ã‚ãŸã‚Šåˆ¤å®š: ja-jp/tutorial/2d-intersection.md
      - 5. ç”»åƒã‚’æã: ja-jp/tutorial/texture.md
      - 6. ãƒ‡ãƒ¼ã‚¿æ§‹é€ : ja-jp/tutorial/data-structures.md
      - 7. æ–‡å­—åˆ—ã¨æ•°å€¤ã®å¤‰æ›: ja-jp/tutorial/formatting.md
      - 8. ãƒ•ã‚©ãƒ³ãƒˆã‚’ä½¿ã†: ja-jp/tutorial/font.md
      - 9. GUI: ja-jp/tutorial/gui.md
      - 10. ã‚·ãƒ¼ãƒ³ã¨ã‚¦ã‚£ãƒ³ãƒ‰ã‚¦: ja-jp/tutorial/window.md
      - 11. ã‚­ãƒ¼ãƒœãƒ¼ãƒ‰å…¥åŠ›: ja-jp/tutorial/keyboard.md
      - 12. ãƒã‚¦ã‚¹å…¥åŠ›: ja-jp/tutorial/mouse.md
      - 13. ã‚ªãƒ¼ãƒ‡ã‚£ã‚ªå†ç”Ÿ: ja-jp/tutorial/audio.md
      - 14. ãƒ©ãƒ³ãƒ€ãƒ : ja-jp/tutorial/random.md
      - 15. 2D ãƒ¬ãƒ³ãƒ€ãƒ¼ã‚¹ãƒ†ãƒ¼ãƒˆ: ja-jp/tutorial/2d-renderstates.md
      - 16. ã‚¨ãƒ•ã‚§ã‚¯ãƒˆ: ja-jp/tutorial/effect.md
      - 17. ã‚¢ã‚»ãƒƒãƒˆç®¡ç†: ja-jp/tutorial/asset.md
      - 18. ãƒ†ã‚­ã‚¹ãƒˆãƒ•ã‚¡ã‚¤ãƒ«: ja-jp/tutorial/text-file.md
      - 19. è¨­å®šãƒ•ã‚¡ã‚¤ãƒ«: ja-jp/tutorial/config-file.md
      - 20. ãƒªã‚½ãƒ¼ã‚¹ã®åŸ‹ã‚è¾¼ã¿: ja-jp/tutorial/resource.md
      - 21. ãƒã‚¤ãƒŠãƒªãƒ•ã‚¡ã‚¤ãƒ«: ja-jp/tutorial/binary-file.md
      - 22. ã‚·ãƒ¼ãƒ³ç®¡ç†: ja-jp/tutorial/scene-manager.md
      - 99. ã‚¢ãƒ—ãƒªã®ãƒªãƒªãƒ¼ã‚¹: ja-jp/tutorial/release.md
    - ãƒªãƒ•ã‚¡ãƒ¬ãƒ³ã‚¹:
      - çµµæ–‡å­—ã®ä¸€è¦§: ja-jp/reference/emojis.md
      - ãƒ•ãƒ«ã‚¹ã‚¯ãƒªãƒ¼ãƒ³: ja-jp/reference/fullscreen.md
      - JSON ãƒ•ã‚¡ã‚¤ãƒ«: ja-jp/reference/json.md
      - æ–‡å­—ã‚³ãƒ¼ãƒ‰ã®å¤‰æ›: ja-jp/reference/unicode.md
      - 2D å›³å½¢ã®å½±: ja-jp/reference/2d-shadow.md
      - 2D è¨ˆç®—å¹¾ä½•: ja-jp/reference/2d-geometry.md
      - ãƒŠãƒ“ãƒ¡ãƒƒã‚·ãƒ¥: ja-jp/reference/navmesh.md
      - è‡ªç„¶è¨€èªå‡¦ç†: ja-jp/reference/nlp.md
      - æ•°å¼å‡¦ç†: ja-jp/reference/math-parser.md
      - kd æœ¨: ja-jp/reference/kd-tree.md
      - ç‰©ä½“æ¤œå‡º: ja-jp/reference/objdetection.md
      - ã‚²ãƒ¼ãƒ ãƒ‘ãƒƒãƒ‰: ja-jp/reference/gamepad.md
      - ãƒãƒƒãƒˆãƒ¯ãƒ¼ã‚¯: ja-jp/reference/network.md
      - Twitter: ja-jp/reference/twitter.md
      - 2D ãƒ‘ãƒ¼ãƒ†ã‚£ã‚¯ãƒ«ã‚·ã‚¹ãƒ†ãƒ : ja-jp/reference/2d-particle.md
      - 2D ç‰©ç†æ¼”ç®—: ja-jp/reference/2d-physics.md
    - ãƒˆãƒ¬ãƒ¼ãƒ‹ãƒ³ã‚°:
      - å††ã‚’é…ç½®ã™ã‚‹: ja-jp/training/1-1.md
      - ä¸‰ç›®ä¸¦ã¹: ja-jp/training/2-1.md
    - API ä¸€è¦§: ja-jp/api/api.md
    - æ–°æ©Ÿèƒ½ç´¹ä»‹:
      - v0.4.1 ã®æ–°æ©Ÿèƒ½: ja-jp/news/v041.md
      - v0.4.2 ã®æ–°æ©Ÿèƒ½: ja-jp/news/v042.md
      - v0.4.3 ã®æ–°æ©Ÿèƒ½: ja-jp/news/v043.md
    - è¨˜äº‹:
      - ã‚ˆãã‚ã‚‹é–“é•ã„: ja-jp/articles/mistakes.md
      - ãƒˆãƒ©ãƒ–ãƒ«ã‚·ãƒ¥ãƒ¼ãƒ†ã‚£ãƒ³ã‚°: ja-jp/articles/troubleshooting.md
      - OpenSiv3D æœ¬ä½“ã®ãƒ“ãƒ«ãƒ‰æ‰‹é †: ja-jp/articles/build.md
      - å‹‰å¼·ä¼šãƒšãƒ¼ã‚¸:
        - ja-jp/articles/event/chiba-2020.md
        - ja-jp/articles/event/ishikawa-2020.md
        - ja-jp/articles/event/sendai-2020.md
    - Siv3D ã‚¹ãƒˆã‚¢: ja-jp/store/store.md
    - ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£:
      - ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£: ja-jp/community/community.md
      - å‹‰å¼·ä¼š: ja-jp/community/study-meeting.md
      - å®Ÿè£…ä¼š: ja-jp/community/dev-day.md
    - ãƒ­ã‚´ç”»åƒ: ja-jp/logo/logo.md
    - ãƒã‚¹ã‚³ãƒƒãƒˆ: ja-jp/mascot/mascot.md
    - ã‚µãƒãƒ¼ãƒˆ: ja-jp/support/support.md
    - å¤–éƒ¨ã‚µã‚¤ãƒˆ: ja-jp/external/external.md
    - ğŸ“¢ ãŠçŸ¥ã‚‰ã›: ja-jp/news/news.md
    - ğŸ’—ã‚¹ãƒãƒ³ã‚µãƒ¼: ja-jp/sponsors/sponsors.md
