site_dir: '../../siv3d.github.io/ja-jp'

# Project information
site_name: Siv3D
site_url: https://siv3d.github.io/ja-jp/
site_author: Ryo Suzuki
site_description: "Siv3D: 創造のための C++ フレームワーク" 

# Repository
repo_name: Siv3D/OpenSiv3D
repo_url: https://github.com/Siv3D/OpenSiv3D

# Copyright
copyright: Copyright (c) 2012 - 2025, Ryo Suzuki<br>Copyright (c) 2012 - 2025, OpenSiv3D Project

# Theme
theme:
  name: material
  language: ja
  palette:
    scheme: siv3d
  logo: 'assets/code-white-48dp.svg'
  favicon: 'assets/favicon.ico'
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.top
  - navigation.footer
  - search.suggest
  - search.highlight
  - content.code.annotate
  - content.code.copy
  plugins:
  - search:
      lang:
        - ja
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
      toc_depth: 2
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  alternate:
    - name: 日本語
      link: https://siv3d.github.io/ja-jp/
      lang: ja
    - name: English
      link: https://siv3d.github.io/en-us/
      lang: en

# Page tree
nav:
  - Siv3D をはじめよう: index.md
  - Siv3D の機能: features.md
  - リリースノート: releases.md
  - ダウンロード:
    - Windows: download/windows.md
    - macOS: download/macos.md
    - Ubuntu: download/ubuntu.md
    - Web: download/web.md
  - チュートリアル 1～20 章:
    - 1. はじめての Siv3D: tutorial/hello.md
    - 2. サンプルを試す: tutorial/samples.md
    - 3. Siv3D の基本: tutorial/basics.md
    - 4. Main 関数とメインループ: tutorial/main.md
    - 5. アプリの基本操作: tutorial/app.md
    - 6. 簡易的な出力: tutorial/print.md
    - 7. 基本的な型とクラス: tutorial/basic-types.md
    - 8. 背景の色を変える: tutorial/background.md
    - 9. 画面と座標: tutorial/scene.md
    - 10. 円を描く: tutorial/circle.md
    - 11. 長方形を描く: tutorial/rect.md
    - 12. 模様を描く: tutorial/pattern.md
    - 13. 絵文字を描く: tutorial/emoji.md
    - 14. 図形や絵文字を動かす: tutorial/motion.md
    - 15. テキストを表示する: tutorial/text.md
    - 16. マウス入力を扱う: tutorial/mouse.md
    - 17. キーボード入力を扱う: tutorial/keyboard.md
    - 18. 乱数を生成する: tutorial/random.md
    - 19. 時間を扱う: tutorial/time.md
    - 20. クリックゲーム: tutorial/click.md
  - チュートリアル 21～40 章:
    - 21. 便利な関数: tutorial2/utility.md
    - 22. 配列: tutorial2/array.md
    - 23. 図形の配列: tutorial2/shape-array.md
    - 24. 図形どうしの交差判定: tutorial2/intersection.md
    - 25. アイテム集めゲーム: tutorial2/collect.md
    - 26. 図形を描く: tutorial2/shape.md
    - 27. 図形の操作: tutorial2/shape-2.md
    - 28. ボタンを作る: tutorial2/button.md
    - 29. クッキークリッカー: tutorial2/cookie-clicker.md
    - 30. 時間と動き: tutorial2/time.md
    - 31. テクスチャを描く: tutorial2/texture.md
    - 32. 動画を描く: tutorial2/video.md
    - 33. 文字列クラス: tutorial2/string.md
    - 34. 文字を描く: tutorial2/font.md
    - 35. 無効値を表現できる型: tutorial2/optional.md
    - 36. 数値と文字列の変換: tutorial2/format.md
    - 37. 二次元配列: tutorial2/grid.md
    - 38. GUI: tutorial2/gui.md
    - 39. ランダム: tutorial2/random.md
    - 40. インタラクションの実装: tutorial2/interaction.md
  - チュートリアル 41～60 章:
    - 41. オーディオ再生: tutorial3/audio.md
    - 42. キーボード入力: tutorial3/keyboard.md
    - 43. マウス入力: tutorial3/mouse.md
    - 44. シーンとウィンドウ: tutorial3/scene.md
    - 45. 図形の交差判定: tutorial3/geometry2d.md
    - 46. ハッシュセット: tutorial3/hashset.md
    - 47. ハッシュテーブル: tutorial3/hashtable.md
    - 48. 2D レンダーステート: tutorial3/2d-render-state.md
    - 49. 2D 座標変換とカメラ: tutorial3/camera2d.md
    - 50. アセット管理: tutorial3/asset.md
    - 51. エフェクト: tutorial3/effect.md
    - 52. レンダーテクスチャ: tutorial3/render-texture.md
    - 53. ファイルシステム: tutorial3/filesystem.md
    - 54. テキストファイル: tutorial3/text-file.md
    - 55. 設定ファイル: tutorial3/config-file.md
    - 56. バイナリファイル: tutorial3/binary-file.md
    - 57. 埋め込みリソース: tutorial3/resource.md
    - 58. シーン管理: tutorial3/scene-manager.md
    - 59. ゲームパッド: tutorial3/gamepad.md
    - 60. アプリの公開: tutorial3/release.md
  - チュートリアル 61～80 章:
    - 61. ファイルダイアログ: tutorial4/file-dialog.md
    - 62. HTTP クライアント: tutorial4/http.md
    - 63. 画像処理: tutorial4/image.md
    - 64. ドラッグ & ドロップ: tutorial4/dragdrop.md
    - 65. クリップボード: tutorial4/clipboard.md
    - 66. ユーザ環境の取得: tutorial4/user.md
    - 67. OpenAI API: tutorial4/openai.md
    - 68. AI 絵しりとり: tutorial4/shiritori.md
    - 69. 2D 物理演算: tutorial4/physics2d.md
    - 70. マイクと音声波形: tutorial4/microphone.md
    - 71. Web カメラ: tutorial4/webcam.md
    - 72. シリアル通信: tutorial4/serial.md
    - 73. OSC 通信: tutorial4/osc.md
    - 74. TCP 通信: tutorial4/tcp.md
    - 75. マルチプレイヤー: tutorial4/multiplayer.md
    - 76. 非同期処理: tutorial4/async.md
    - 77. 数式パーサー: tutorial4/mathparser.md
    - 78. QR コード: tutorial4/qr.md
    - 79. テキスト読み上げ: tutorial4/tts.md
    - 80. 効率的な描画: tutorial4/performance.md
  - チュートリアル 81～ 章:
    - 81. メッセージボックス: tutorial5/messagebox.md
    - 今後の更新予定: tutorial5/wip.md
#    - 81. 2D カスタムシェーダ: tutorial5/empty.md
#    - 82. 3D 形状を描く ①: tutorial5/empty.md
#    - 83. 3D 形状を描く ②: tutorial5/empty.md
#    - 84. 3D の交差判定: tutorial5/empty.md
  - サンプル集:
    - ゲームのサンプル: samples/games.md
    - アプリケーションのサンプル: samples/apps.md
    - Web サービスとの連係サンプル: samples/web.md
    - 図形のサンプル: samples/shapes.md
    - 2D 描画のサンプル: samples/2d.md
    - 画像のサンプル: samples/image.md
    - 文字表示のサンプル: samples/text.md
    - UI のサンプル: samples/ui.md
    - データ可視化のサンプル: samples/visualize.md
    - モーショングラフィックスのサンプル: samples/motion-graphics.md
    - アドオンのサンプル: samples/addon.md
    - 音のサンプル: samples/sound.md
    - 2D 物理演算のサンプル: samples/physics2d.md
    - 3D 描画のサンプル: samples/3d.md
    - ゲームランチャーを作る: samples/gamelauncher.md
  - コース:
    - 電卓アプリを作る: course/calculator.md
    - 多態性の活用: course/polymorphism.md
    - レーダーチャート: course/radar-chart.md
    - 奥行き型 UI の作成: course/quadwarp.md
  - API:
    - クラス一覧: api/classes.md
  - 記事:
    - プロジェクトを GitHub で管理する: reference/github.md
    - ゲーム開発のヒント集: reference/game_tips.md
    - メッセージボックス: reference/messagebox.md
    - 自作クラスと Siv3D の連係: reference/adapter.md
    - Siv3D で Hello world する 21 の方法: reference/helloworld.md
    - グローバル変数として作成できないクラス: reference/avoid-global-variable.md
    - 多態性を使ったクラスの実装: reference/polymorphism.md
  - コミュニティ:
    - コミュニティ: community/community.md
    - これまでのイベント: community/history.md
  - 開発に便利なツール:
    - Siv3D Palette Browser: tools/palette.md
    - 絵文字とアイコンの検索: tools/emoji.md
    - Easing Functions Cheat Sheet: tools/easing.md
    - GitHub Gist: tools/gist.md
    - Cosense: tools/cosense.md
    - Xbox Game Bar : tools/gamebar.md
    - VSColorOutput: tools/vscoloroutput.md
    - .gitignore: tools/gitignore.md
    - ホットリロード: tools/hot-reload.md
    - 例外の発生個所の表示: tools/msvc-exception.md
  - 開発に参加する:
    - 報告や提案: develop/report.md
    - 自前ビルドの手順: develop/build.md
    - コントリビューションガイド: develop/commit.md
    - コーディングスタイル: develop/coding-style.md
  - イベント:
    - ゲームジャム 2025: event/gamejam.md
    - ゲームジャム 2025 入賞作品: event/gamejam2025.md
    - ゲームジャム 2023: event/gamejam2023info.md
    - ゲームジャム 2023 入賞作品: event/gamejam2023.md
  - 協賛企業の募集:
    - 協賛企業の募集について: sponsorship/corporate-sponsor.md
    - 協賛特典: sponsorship/corporate-sponsor-guideline.md
  - Steam: steam.md
  - Siv3D くん: mascot.md
  - 社会貢献: social-contribution.md
  - 謝辞: acknowledgments.md
  - お問い合わせ: contact.md
